/// @desc Contains all the macros
// Debug logging
#macro LOG_GLOBAL_MAX_MESSAGES 25
#macro LOG_INSTANCE_MAX_MESSAGES 100
#macro LOG_GLOBAL noone
#macro LOG_MESSAGE_TIME_ON_SCREEN 100
#macro LOG_MESSAGE_FADE_TIME 50

// State machine
#macro ON_STATE_ENTER 0
#macro ON_STATE_UPDATE 1
#macro ON_STATE_EXIT 2

// Collisions
#macro TILE_VOID 0
#macro TILE_SOLID 1
#macro TILE_RSLOPE 2
#macro TILE_LSLOPE 3
#macro TILE_RSLOPE_SMALL_START 4
#macro TILE_RSLOPE_SMALL_END 5
#macro TILE_LSLOPE_SMALL_END 6
#macro TILE_LSLOPE_SMALL_START 7
#macro TILE_PLATFORM 8

// Camera
#macro CAMERA_SHAKE_TRANSLATIONAL_REFERENCE 20
#macro CAMERA_SHAKE_ROTATIONAL_REFERENCE 45
