/// @desc Contains all the macros
// Debug logging
#macro LOG_GLOBAL_MAX_MESSAGES 25
#macro LOG_INSTANCE_MAX_MESSAGES 100
#macro LOG_GLOBAL noone
#macro LOG_MESSAGE_TIME_ON_SCREEN 100
#macro LOG_MESSAGE_FADE_TIME 50

// Debug drawing
#macro DEBUG_RECT_X1 1
#macro DEBUG_RECT_Y1 2
#macro DEBUG_RECT_X2 3
#macro DEBUG_RECT_Y2 4
#macro DEBUG_RECT_COLOR 5
#macro DEBUG_RECT_ALPHA 6
#macro DEBUG_RECT_FILLED_FLAG 7

#macro DEBUG_CIRCLE_X 1
#macro DEBUG_CIRCLE_Y 2
#macro DEBUG_CIRCLE_RADIUS 3
#macro DEBUG_CIRCLE_COLOR 4
#macro DEBUG_CIRCLE_ALPHA 5
#macro DEBUG_CIRCLE_FILLED_FLAG 6

#macro DEBUG_LINE_X1 1
#macro DEBUG_LINE_Y1 2
#macro DEBUG_LINE_X2 3
#macro DEBUG_LINE_Y2 4
#macro DEBUG_LINE_COLOR 5
#macro DEBUG_LINE_ALPHA 6

#macro DEBUG_ARROW_X1 1
#macro DEBUG_ARROW_Y1 2
#macro DEBUG_ARROW_X2 3
#macro DEBUG_ARROW_Y2 4
#macro DEBUG_ARROW_SIZE 5
#macro DEBUG_ARROW_COLOR 6
#macro DEBUG_ARROW_ALPHA 7

#macro DEBUG_TEXT_X 1
#macro DEBUG_TEXT_Y 2
#macro DEBUG_TEXT_DATA 3
#macro DEBUG_TEXT_SIZE 4
#macro DEBUG_TEXT_COLOR 5
#macro DEBUG_TEXT_ALPHA 6
#macro DEBUG_TEXT_HALIGN 7
#macro DEBUG_TEXT_VALIGN 8

// State machine
#macro ON_STATE_ENTER 0
#macro ON_STATE_UPDATE 1
#macro ON_STATE_EXIT 2

// Animation system
#macro ANIM_SPRITE_INDEX 0
#macro ANIM_LOOP_MODE 1
#macro ANIM_SPEED 2
#macro ANIM_FRAME_EVENTS 3

// Camera
#macro CAMERA_SHAKE_TRANSLATIONAL_REFERENCE 20
#macro CAMERA_SHAKE_ROTATIONAL_REFERENCE 45
